### ISSUE TITLE
Disabling components

### ISSUE THREAD

**Issue by Kernald** [lewisdoesstuff/bento-next#2]
**Is your feature request related to a problem? Please describe.**
There are things that I would like _not_ to use (namely, the greetings block and the theme selector in the top-right). Having a way to disable them would be great.

**Describe the solution you'd like**
A boolean entry in the configuration to skip a section.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by lewisdoesstuff** [comment]
Just pushed this to master :)

See the section in the README for more details, but just set the specific component to `false` in your `config.js`.

For the theme button, I'm not sure if you wanted to specifically disable the dropdown and the arrow prompt, or the button entirely. At the moment, this removes the sun/moon icon as well, but if you want it more specifically on the drop-down, just let me know :)

**Comment by Kernald** [comment]
Cheers, that's exactly what I had in mind, thanks for the very quick fix :-)
